#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.12f1_0a46ddfcfad4"
#define UNITY_VERSION_FULL_NICE "2018.2.12f1 (0a46ddfcfad4)"
#define UNITY_VERSION_BLD 673501
#define UNITY_VERSION_DATE 1538732320
#define UNITY_VERSION_WIN "2018.2.12.673501"
#define UNITY_VERSION_BRANCH "2018.2/release"
